添加 "Kotlin 基础语法" 文章
kaixueio/kaixue-docs pull request #6
Opened 2019-04-04 09:39 UTC by bruce3x

2019-04-08 03:02 UTC, rengwuxian commented on 文章/Kotlin-1-基本语法/kotlin_basic_grammar.md
> +  	is Int -> print("x is Int")
这个是不是多了一个 TAB

2019-04-08 03:07 UTC, bruce3x commented on 文章/Kotlin-1-基本语法/kotlin_basic_grammar.md
> +  	is Int -> print("x is Int")
是的。。

2019-04-22 08:12 UTC, rengwuxian commented on 文章/Kotlin-1-基本语法/kotlin_basic.md
> +Kotlin 中的字符类型不能直接当作数字来用，不能与数字进行比较或者赋值，需要通过 `Chat.toInt()` 或 `Int.toChar()` 转换才行。
`Chat.toInt()` -> `Char.toInt()`

2019-04-22 08:16 UTC, rengwuxian commented on 文章/Kotlin-1-基本语法/kotlin_basic.md
> +`when` 可是视作 Kotlin 中的 switch 语句。每一条分支的值，可以是常量或表达式。
可以视作

2019-04-22 08:30 UTC, rengwuxian requested changes
when{ -> when {

顺手试试 GitHub 现在的 Review 工具…… 😂

2019-04-22 08:30 UTC, rengwuxian commented on 文章/Kotlin-1-基本语法/kotlin_basic.md
> +when{
`when{` -> `when {`

2019-04-22 08:39 UTC, rengwuxian commented
这篇概览很好啊，大佬大佬。

另外嗯……这个的定位是概览吧？如果是的话，标题是不是改成「Kotlin 基础语法概览」、「Kotlin 常见于法概览」，并且在文章的开头声明类似「这是一篇概览，目的是让想了解 Kotlin 『到底有多方便』和『到底有多难上手』的人有一个大致的快速感受。具体的细节，如果你对 Kotlin 有兴趣，可以看后面的每一篇文章」的话，并在结尾再次勾引一下「Kotlin 基础语法大致就长这个样子，如果需要了解更多，欢迎继续关注本系列」之类的话。

这样写的话，读者会在读的过程中有较轻松的感觉「不用学会，感受一下就好」，并且在遇到写得不详细的地方，由于有了「概览」这个语气，所以也会想「嗯，应该是故意只写了个大概的，我继续往下看就行」，而不是误解作者，觉得「哼哼，就这？」。

2019-04-22 08:49 UTC, bruce3x commented
哈哈，凯哥过奖了。

之前还没想好这篇文章的标题，现在觉得这个 「Kotlin 基础语法概览」还挺合适的~ 我来把文章首尾完善一下。😁

2019-04-22 12:10 UTC, rengwuxian commented
LGTM!

2019-04-22 12:30 UTC, bruce3x commented
还有什么需要修改的吗？ 我看 PR 状态还是 「Changes requested」😂

2019-04-22 13:13 UTC, rengwuxian commented
我不知道，我现在在手机上。你看看没问题就合了吧？:smile:

2019-04-23 03:34 UTC, hamberluo approved these changes

2019-04-23 03:43 UTC, merged